# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'SynerzipTest' do

end

target 'UI Tests', :exclusive => true do
  pod 'KIF/OCUnit', '~> 3.0'
end